### ISSUE TITLE
发现css内部图片地址的路径，集成到html后，路径会变错

### ISSUE THREAD

**Issue by jiachenlee** [amfe/or.htmlone.gulp#1]
如题，希望可以帮忙解决，多谢
如css/a.css中
background:url(../img/index_header.png)
生成到html中,路径没有变化
background:url(../img/index_header.png)

**Comment by hongru** [comment]
不好意思，github的issue 跟进的比较晚。现在npm上已经更新到 0.1.6 版本了，修复了一些bug，详见 https://www.npmjs.com/package/gulp-htmlone  。具体你用的哪个版本不太确定，建议更新到最新的再试试。如果还有问题 最好贴上文件的用例，我可以再跟进下

**Comment by jiachenlee** [comment]
感谢你的修改：）
